# Use root/example as user/password credentials
version: '3'

services:

  mongo:
    image: mongo:latest
    restart: always
    ports: 
        - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
      

  app:
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    ports: 
      - "8080:8080"
    restart: always
    
    

